// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrungTamNgoaiNgu.Data;

#nullable disable

namespace TrungTamNgoaiNgu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305210753_SyncSchemaFromSql10_20260306")]
    partial class SyncSchemaFromSql10_20260306
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaiVietDanhMucBaiViet", b =>
                {
                    b.Property<int>("BaiVietsBaiVietId")
                        .HasColumnType("int");

                    b.Property<int>("DanhMucsDanhMucId")
                        .HasColumnType("int");

                    b.HasKey("BaiVietsBaiVietId", "DanhMucsDanhMucId");

                    b.HasIndex("DanhMucsDanhMucId");

                    b.ToTable("baiviet_danhmuc", (string)null);
                });

            modelBuilder.Entity("BaiVietTag", b =>
                {
                    b.Property<int>("BaiVietsBaiVietId")
                        .HasColumnType("int");

                    b.Property<long>("TagsTagId")
                        .HasColumnType("bigint");

                    b.HasKey("BaiVietsBaiVietId", "TagsTagId");

                    b.HasIndex("TagsTagId");

                    b.ToTable("baiviet_tag", (string)null);
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.BaiViet", b =>
                {
                    b.Property<int>("BaiVietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("baiVietId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BaiVietId"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("anhDaiDien");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int")
                        .HasColumnName("luotXem");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<string>("TomTat")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tomTat");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("BaiVietId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("baiviet");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.BuoiHoc", b =>
                {
                    b.Property<int>("BuoiHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("buoiHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuoiHocId"));

                    b.Property<int?>("CaHocId")
                        .HasColumnType("int")
                        .HasColumnName("caHocId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaDiemDanh")
                        .HasColumnType("bit")
                        .HasColumnName("daDiemDanh");

                    b.Property<bool>("DaHoanThanh")
                        .HasColumnType("bit")
                        .HasColumnName("daHoanThanh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("lopHocId");

                    b.Property<DateOnly?>("NgayHoc")
                        .HasColumnType("date")
                        .HasColumnName("ngayHoc");

                    b.Property<int?>("PhongHocId")
                        .HasColumnType("int")
                        .HasColumnName("phongHocId");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("TenBuoiHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenBuoiHoc");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("BuoiHocId");

                    b.HasIndex("CaHocId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("PhongHocId");

                    b.ToTable("buoihoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.CaHoc", b =>
                {
                    b.Property<int>("CaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("caHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaHocId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gioBatDau");

                    b.Property<TimeOnly?>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("gioKetThuc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenCa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenCa");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("CaHocId");

                    b.ToTable("cahoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.CoSoDaoTao", b =>
                {
                    b.Property<int>("CoSoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coSoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoSoId"));

                    b.Property<string>("BanDoGoogle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("banDoGoogle");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<decimal?>("KinhDo")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("kinhDo");

                    b.Property<string>("MaCoSo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maCoSo");

                    b.Property<DateOnly?>("NgayKhaiTruong")
                        .HasColumnType("date")
                        .HasColumnName("ngayKhaiTruong");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("slug");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TenCoSo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenCoSo");

                    b.Property<string>("TenPhuongXa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("tenPhuongXa");

                    b.Property<int?>("TinhThanhId")
                        .HasColumnType("int")
                        .HasColumnName("tinhThanhId");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("ViDo")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("viDo");

                    b.HasKey("CoSoId");

                    b.HasIndex("TinhThanhId");

                    b.ToTable("cosodaotao");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DangKyLopHoc", b =>
                {
                    b.Property<int>("DangKyLopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dangKyLopHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyLopHocId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("lopHocId");

                    b.Property<DateOnly?>("NgayDangKy")
                        .HasColumnType("date")
                        .HasColumnName("ngayDangKy");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DangKyLopHocId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("dangkylophoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DanhMucBaiViet", b =>
                {
                    b.Property<int>("DanhMucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("danhMucId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDanhMuc");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DanhMucId");

                    b.ToTable("danhmucbaiviet");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DanhMucKhoaHoc", b =>
                {
                    b.Property<int>("DanhMucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("danhMucId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDanhMuc");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DanhMucId");

                    b.HasIndex("ParentId");

                    b.ToTable("danhmuckhoahoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DiemDanh", b =>
                {
                    b.Property<string>("DiemDanhId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("diemDanhId");

                    b.Property<int?>("BuoiHocId")
                        .HasColumnType("int")
                        .HasColumnName("buoiHocId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("DiemDanhId");

                    b.HasIndex("BuoiHocId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("diemdanh");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HoSoNguoiDung", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("anhDaiDien");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("diaChi");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("MoiQuanHe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("moiQuanHe");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngaySinh");

                    b.Property<string>("NgonNguMucTieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ngonNguMucTieu");

                    b.Property<string>("NguoiGiamHo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nguoiGiamHo");

                    b.Property<string>("NguonBietDen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nguonBietDen");

                    b.Property<string>("SdtGuardian")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sdtGuardian");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<string>("TrinhDoHienTai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("trinhDoHienTai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zalo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zalo");

                    b.HasKey("TaiKhoanId");

                    b.ToTable("hosonguoidung");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hoaDonId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<int?>("CoSoId")
                        .HasColumnType("int")
                        .HasColumnName("coSoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DaTra")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("daTra");

                    b.Property<int?>("DangKyLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("dangKyLopHocId");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("giamGia");

                    b.Property<byte>("LoaiHoaDon")
                        .HasColumnType("tinyint")
                        .HasColumnName("loaiHoaDon");

                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maHoaDon");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("ngayHetHan");

                    b.Property<DateOnly?>("NgayLap")
                        .HasColumnType("date")
                        .HasColumnName("ngayLap");

                    b.Property<int?>("PhuongThucThanhToan")
                        .HasColumnType("int")
                        .HasColumnName("phuongThucThanhToan");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<decimal>("Thue")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("thue");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tongTien");

                    b.Property<decimal>("TongTienSauThue")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tongTienSauThue");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("HoaDonId");

                    b.HasIndex("CoSoId");

                    b.HasIndex("DangKyLopHocId")
                        .IsUnique()
                        .HasFilter("[dangKyLopHocId] IS NOT NULL");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("hoadon");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HocPhi", b =>
                {
                    b.Property<long>("HocPhiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("hocPhiId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HocPhiId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("donGia");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("khoaHocId");

                    b.Property<int?>("SoBuoi")
                        .HasColumnType("int")
                        .HasColumnName("soBuoi");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("HocPhiId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("hocphi");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("khoaHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaHocId"));

                    b.Property<string>("AnhKhoaHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("anhKhoaHoc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int")
                        .HasColumnName("danhMucId");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DoiTuong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doiTuong");

                    b.Property<string>("KetQuaDatDuoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ketQuaDatDuoc");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenKhoaHoc");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("YeuCauDauVao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("yeuCauDauVao");

                    b.HasKey("KhoaHocId");

                    b.HasIndex("DanhMucId");

                    b.ToTable("khoahoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LienHe", b =>
                {
                    b.Property<int>("LienHeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lienHeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LienHeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("GhiChuNoiBo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChuNoiBo");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hoTen");

                    b.Property<string>("LoaiLienHe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("tu_van")
                        .HasColumnName("loaiLienHe");

                    b.Property<long?>("NguoiPhuTrachId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoiPhuTrachId");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("soDienThoai");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<DateTime?>("ThoiGianXuLy")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianXuLy");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LienHeId");

                    b.ToTable("lienhe");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LienHeLichSu", b =>
                {
                    b.Property<long>("LichSuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("lichSuId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LichSuId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("GiaTriCu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("giaTriCu");

                    b.Property<string>("GiaTriMoi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("giaTriMoi");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hanhDong");

                    b.Property<long>("LienHeId")
                        .HasColumnType("bigint")
                        .HasColumnName("lienHeId");

                    b.Property<long?>("NguoiThucHienId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoiThucHienId");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<string>("TenNguoiThucHien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenNguoiThucHien");

                    b.HasKey("LichSuId");

                    b.HasIndex("LienHeId");

                    b.ToTable("lienhe_lichsu");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LienHePhanHoi", b =>
                {
                    b.Property<long>("PhanHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("phanHoiId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PhanHoiId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaGuiEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daGuiEmail");

                    b.Property<long>("LienHeId")
                        .HasColumnType("bigint")
                        .HasColumnName("lienHeId");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("noi_bo")
                        .HasColumnName("loai");

                    b.Property<long?>("NguoiGuiId")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoiGuiId");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<string>("TenNguoiGui")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tenNguoiGui");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PhanHoiId");

                    b.HasIndex("LienHeId");

                    b.ToTable("lienhe_phanhoi");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LopHoc", b =>
                {
                    b.Property<int>("LopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lopHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocId"));

                    b.Property<int>("CaHocId")
                        .HasColumnType("int")
                        .HasColumnName("caHocId");

                    b.Property<int?>("CoSoId")
                        .HasColumnType("int")
                        .HasColumnName("coSoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DonGiaDay")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("donGiaDay");

                    b.Property<long?>("HocPhiId")
                        .HasColumnType("bigint")
                        .HasColumnName("hocPhiId");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("khoaHocId");

                    b.Property<string>("LichHoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lichHoc");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngayBatDau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngayKetThuc");

                    b.Property<int?>("PhongHocId")
                        .HasColumnType("int")
                        .HasColumnName("phongHocId");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<int?>("SoBuoiDuKien")
                        .HasColumnType("int")
                        .HasColumnName("soBuoiDuKien");

                    b.Property<int?>("SoHocVienToiDa")
                        .HasColumnType("int")
                        .HasColumnName("soHocVienToiDa");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("TenLopHoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenLopHoc");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LopHocId");

                    b.HasIndex("CaHocId");

                    b.HasIndex("CoSoId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("PhongHocId");

                    b.ToTable("lophoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.Luong", b =>
                {
                    b.Property<int>("LuongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luongId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuongId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date")
                        .HasColumnName("ngayThanhToan");

                    b.Property<decimal>("Phat")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("phat");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("phuCap");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("ThangLuong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("thangLuong");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("thuong");

                    b.Property<int?>("TongBuoiDay")
                        .HasColumnType("int")
                        .HasColumnName("tongBuoiDay");

                    b.Property<decimal?>("TongLuongDay")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tongLuongDay");

                    b.Property<decimal?>("TongTienThucLanh")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tongTienThucLanh");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LuongId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("luong");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LuongChiTiet", b =>
                {
                    b.Property<int>("LuongChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("luongChiTietId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LuongChiTietId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DonGiaMotBuoi")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("donGiaMotBuoi");

                    b.Property<int?>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("lopHocId");

                    b.Property<int?>("LuongId")
                        .HasColumnType("int")
                        .HasColumnName("luongId");

                    b.Property<int?>("SoBuoiDay")
                        .HasColumnType("int")
                        .HasColumnName("soBuoiDay");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tongTien");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("LuongChiTietId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("LuongId");

                    b.ToTable("luongchitiet");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.NhanSu", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<string>("BangCap")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bangCap");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("chucVu");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chuyenMon");

                    b.Property<int?>("CoSoId")
                        .HasColumnType("int")
                        .HasColumnName("coSoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("HocVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hocVi");

                    b.Property<string>("LoaiHopDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("loaiHopDong");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("luongCoBan");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maNhanVien");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date")
                        .HasColumnName("ngayVaoLam");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("CoSoId");

                    b.ToTable("nhansu");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.NhatKyHeThong", b =>
                {
                    b.Property<long>("NhatKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("nhatKyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NhatKyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("hanhDong");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nguoiThucHien");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.HasKey("NhatKyId");

                    b.ToTable("nhatkyhethong");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.NhomQuyen", b =>
                {
                    b.Property<int>("NhomQuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nhomQuyenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhomQuyenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("moTa");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenNhom");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("NhomQuyenId");

                    b.ToTable("nhomquyen");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhanQuyen", b =>
                {
                    b.Property<int>("PhanQuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phanQuyenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhanQuyenId"));

                    b.Property<bool>("CoSua")
                        .HasColumnType("bit")
                        .HasColumnName("coSua");

                    b.Property<bool>("CoThem")
                        .HasColumnType("bit")
                        .HasColumnName("coThem");

                    b.Property<bool>("CoXem")
                        .HasColumnType("bit")
                        .HasColumnName("coXem");

                    b.Property<bool>("CoXoa")
                        .HasColumnType("bit")
                        .HasColumnName("coXoa");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("NhomQuyenId")
                        .HasColumnType("int")
                        .HasColumnName("nhomQuyenId");

                    b.Property<string>("TinhNang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tinhNang");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PhanQuyenId");

                    b.HasIndex("NhomQuyenId");

                    b.ToTable("phanquyen");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhieuThu", b =>
                {
                    b.Property<long>("PhieuThuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("phieuThuId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PhieuThuId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int")
                        .HasColumnName("hoaDonId");

                    b.Property<string>("MaPhieuThu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maPhieuThu");

                    b.Property<DateOnly?>("NgayThu")
                        .HasColumnType("date")
                        .HasColumnName("ngayThu");

                    b.Property<byte>("PhuongThucThanhToan")
                        .HasColumnType("tinyint")
                        .HasColumnName("phuongThucThanhToan");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("soTien");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PhieuThuId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("phieuthu");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhongHoc", b =>
                {
                    b.Property<int>("PhongHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phongHocId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongHocId"));

                    b.Property<int?>("CoSoId")
                        .HasColumnType("int")
                        .HasColumnName("coSoId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("sucChua");

                    b.Property<string>("TenPhong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenPhong");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trangThai");

                    b.Property<string>("TrangThietBi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangThietBi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PhongHocId");

                    b.HasIndex("CoSoId");

                    b.ToTable("phonghoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("display_name");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("group");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("nvarchar(191)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tagId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("slug");

                    b.Property<string>("TenTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenTag");

                    b.HasKey("TagId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.TaiKhoan", b =>
                {
                    b.Property<int>("TaiKhoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiKhoanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastLogin");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<int?>("NhomQuyenId")
                        .HasColumnType("int")
                        .HasColumnName("nhomQuyenId");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("taiKhoan");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TaiKhoanId");

                    b.HasIndex("NhomQuyenId");

                    b.ToTable("taikhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBao", b =>
                {
                    b.Property<int>("ThongBaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("thongBaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte?>("DoiTuongGui")
                        .HasColumnType("tinyint")
                        .HasColumnName("doiTuongGui");

                    b.Property<int?>("DoiTuongId")
                        .HasColumnType("int")
                        .HasColumnName("doiTuongId");

                    b.Property<bool>("Ghim")
                        .HasColumnType("bit")
                        .HasColumnName("ghim");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinhAnh");

                    b.Property<byte>("LoaiGui")
                        .HasColumnType("tinyint")
                        .HasColumnName("loaiGui");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayGui");

                    b.Property<int?>("NguoiGuiId")
                        .HasColumnType("int")
                        .HasColumnName("nguoiGuiId");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<byte?>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<byte>("UuTien")
                        .HasColumnType("tinyint")
                        .HasColumnName("uuTien");

                    b.HasKey("ThongBaoId");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("thongbao");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBaoNguoiDung", b =>
                {
                    b.Property<int>("ThongBaoNguoiDungId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("thongBaoNguoiDungId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThongBaoNguoiDungId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit")
                        .HasColumnName("daDoc");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayDoc");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("taiKhoanId");

                    b.Property<int?>("ThongBaoId")
                        .HasColumnType("int")
                        .HasColumnName("thongBaoId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ThongBaoNguoiDungId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("thongbaonguoidung");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBaoTepDinh", b =>
                {
                    b.Property<long>("TepDinhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tepDinhId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TepDinhId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("duongDan");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint")
                        .HasColumnName("kichThuoc");

                    b.Property<string>("LoaiFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loaiFile");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenFile");

                    b.Property<string>("TenFileLuu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenFileLuu");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int")
                        .HasColumnName("thongBaoId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TepDinhId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("thongbao_tepdinh");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.TinhThanh", b =>
                {
                    b.Property<int>("TinhThanhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tinhThanhId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TinhThanhId"));

                    b.Property<string>("Codename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("codename");

                    b.Property<string>("DivisionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("division_type");

                    b.Property<int?>("MaAPI")
                        .HasColumnType("int")
                        .HasColumnName("maAPI");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("TenTinhThanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenTinhThanh");

                    b.HasKey("TinhThanhId");

                    b.ToTable("tinhthanh");
                });

            modelBuilder.Entity("BaiVietDanhMucBaiViet", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.BaiViet", null)
                        .WithMany()
                        .HasForeignKey("BaiVietsBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrungTamNgoaiNgu.Models.DanhMucBaiViet", null)
                        .WithMany()
                        .HasForeignKey("DanhMucsDanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BaiVietTag", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.BaiViet", null)
                        .WithMany()
                        .HasForeignKey("BaiVietsBaiVietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrungTamNgoaiNgu.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.BaiViet", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TacGia")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.BuoiHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.CaHoc", "CaHoc")
                        .WithMany()
                        .HasForeignKey("CaHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.LopHoc", "LopHoc")
                        .WithMany("BuoiHocs")
                        .HasForeignKey("LopHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("PhongHocId");

                    b.Navigation("CaHoc");

                    b.Navigation("LopHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.CoSoDaoTao", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TinhThanh", "TinhThanh")
                        .WithMany("CoSos")
                        .HasForeignKey("TinhThanhId");

                    b.Navigation("TinhThanh");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DangKyLopHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.LopHoc", "LopHoc")
                        .WithMany("DangKys")
                        .HasForeignKey("LopHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DanhMucKhoaHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.DanhMucKhoaHoc", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DiemDanh", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.BuoiHoc", "BuoiHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("BuoiHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("BuoiHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HoSoNguoiDung", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HoSo")
                        .HasForeignKey("TrungTamNgoaiNgu.Models.HoSoNguoiDung", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HoaDon", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.CoSoDaoTao", "CoSo")
                        .WithMany()
                        .HasForeignKey("CoSoId");

                    b.HasOne("TrungTamNgoaiNgu.Models.DangKyLopHoc", "DangKyLopHoc")
                        .WithOne("HoaDon")
                        .HasForeignKey("TrungTamNgoaiNgu.Models.HoaDon", "DangKyLopHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("CoSo");

                    b.Navigation("DangKyLopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HocPhi", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("HocPhis")
                        .HasForeignKey("KhoaHocId");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.KhoaHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.DanhMucKhoaHoc", "DanhMuc")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("DanhMucId");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LopHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.CaHoc", "CaHoc")
                        .WithMany()
                        .HasForeignKey("CaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrungTamNgoaiNgu.Models.CoSoDaoTao", "CoSo")
                        .WithMany("LopHocs")
                        .HasForeignKey("CoSoId");

                    b.HasOne("TrungTamNgoaiNgu.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("LopHocs")
                        .HasForeignKey("KhoaHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("PhongHocId");

                    b.Navigation("CaHoc");

                    b.Navigation("CoSo");

                    b.Navigation("KhoaHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.Luong", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LuongChiTiet", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId");

                    b.HasOne("TrungTamNgoaiNgu.Models.Luong", "Luong")
                        .WithMany("ChiTiets")
                        .HasForeignKey("LuongId");

                    b.Navigation("LopHoc");

                    b.Navigation("Luong");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.NhanSu", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.CoSoDaoTao", "CoSo")
                        .WithMany()
                        .HasForeignKey("CoSoId");

                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NhanSu")
                        .HasForeignKey("TrungTamNgoaiNgu.Models.NhanSu", "TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoSo");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhanQuyen", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.NhomQuyen", "NhomQuyen")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("NhomQuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhieuThu", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuThus")
                        .HasForeignKey("HoaDonId");

                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "NguoiThu")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("HoaDon");

                    b.Navigation("NguoiThu");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.PhongHoc", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.CoSoDaoTao", "CoSo")
                        .WithMany("PhongHocs")
                        .HasForeignKey("CoSoId");

                    b.Navigation("CoSo");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.TaiKhoan", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.NhomQuyen", "NhomQuyen")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("NhomQuyenId");

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBao", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId");

                    b.Navigation("NguoiGui");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBaoNguoiDung", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("TrungTamNgoaiNgu.Models.ThongBao", "ThongBao")
                        .WithMany("ThongBaoNguoiDungs")
                        .HasForeignKey("ThongBaoId");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBaoTepDinh", b =>
                {
                    b.HasOne("TrungTamNgoaiNgu.Models.ThongBao", "ThongBao")
                        .WithMany("TepDinhs")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.BuoiHoc", b =>
                {
                    b.Navigation("DiemDanhs");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.CoSoDaoTao", b =>
                {
                    b.Navigation("LopHocs");

                    b.Navigation("PhongHocs");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DangKyLopHoc", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.DanhMucKhoaHoc", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("KhoaHocs");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.HoaDon", b =>
                {
                    b.Navigation("PhieuThus");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.KhoaHoc", b =>
                {
                    b.Navigation("HocPhis");

                    b.Navigation("LopHocs");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.LopHoc", b =>
                {
                    b.Navigation("BuoiHocs");

                    b.Navigation("DangKys");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.Luong", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.NhomQuyen", b =>
                {
                    b.Navigation("PhanQuyens");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.TaiKhoan", b =>
                {
                    b.Navigation("HoSo");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.ThongBao", b =>
                {
                    b.Navigation("TepDinhs");

                    b.Navigation("ThongBaoNguoiDungs");
                });

            modelBuilder.Entity("TrungTamNgoaiNgu.Models.TinhThanh", b =>
                {
                    b.Navigation("CoSos");
                });
#pragma warning restore 612, 618
        }
    }
}
